-- Custom SQL migration file, put your code below! --

-- Maintain `ranklist_user.score` and `.rank` entirely in the database.
--
-- score(user U in ranklist R) = SUM over events E in R of:
--   * strict-attendance exception: when R.consider_strict_attendance = 1 AND
--     E.strict_attendance = 1 AND U has no attendance row for E, solves count as
--     upsolves -> (solve + upsolve) * weight * upsolve_weight
--   * otherwise -> solve * weight + upsolve * weight * upsolve_weight
-- rank = 1 + (count of users in R with a strictly greater score) -> competition
-- ranking (1,2,2,4); bigger score = lower number, starting at 1. is_locked is ignored.
--
-- The score subquery and the rank subquery both correlate to the outer `ranklist_user`
-- row, so the SAME two expressions are reused in every statement below; only the WHERE
-- scope differs. A narrow score scope is paired with a ranklist-wide re-rank scope,
-- because one user's score change shifts every other user's rank in that ranklist.
--
-- NOTE: each CREATE TRIGGER is on a single line on purpose (see the count-triggers
-- migration) — some SQLite runners split a SQL blob on ";\n", which would chop a
-- multi-line BEGIN…END body apart.
--
-- No recursion: every trigger only ever runs `UPDATE ranklist_user SET score/rank`,
-- and no trigger here (nor the count-triggers migration's, scoped `OF ranklist_id`)
-- fires on a ranklist_user UPDATE of score/rank, so the bodies cannot re-trigger one another.

-- Backfill existing rows: scores first, then ranks (ranks depend on final scores).
UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id);
--> statement-breakpoint
UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score));
--> statement-breakpoint
CREATE TRIGGER `rl_score_ep_ai` AFTER INSERT ON `event_performance` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE user_id = NEW.user_id AND ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ep_au` AFTER UPDATE OF `solve_count`, `upsolve_count` ON `event_performance` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE user_id = NEW.user_id AND ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ep_ad` AFTER DELETE ON `event_performance` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE user_id = OLD.user_id AND ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = OLD.event_id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = OLD.event_id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ea_ai` AFTER INSERT ON `event_attendance` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE user_id = NEW.user_id AND ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.event_id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ea_ad` AFTER DELETE ON `event_attendance` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE user_id = OLD.user_id AND ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = OLD.event_id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = OLD.event_id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_re_ai` AFTER INSERT ON `ranklist_event` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id = NEW.ranklist_id; UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = NEW.ranklist_id; END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_re_ad` AFTER DELETE ON `ranklist_event` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id = OLD.ranklist_id; UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = OLD.ranklist_id; END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_re_au` AFTER UPDATE OF `weight` ON `ranklist_event` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id = NEW.ranklist_id; UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = NEW.ranklist_id; END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_rl_au` AFTER UPDATE OF `upsolve_weight`, `consider_strict_attendance` ON `ranklists` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id = NEW.id; UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = NEW.id; END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ev_au` AFTER UPDATE OF `strict_attendance` ON `events` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.id); UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id IN (SELECT ranklist_id FROM ranklist_event WHERE event_id = NEW.id); END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ru_ai` AFTER INSERT ON `ranklist_user` BEGIN UPDATE ranklist_user SET score = (SELECT COALESCE(SUM(CASE WHEN rl.consider_strict_attendance = 1 AND e.strict_attendance = 1 AND NOT EXISTS (SELECT 1 FROM event_attendance ea WHERE ea.event_id = ep.event_id AND ea.user_id = ep.user_id) THEN (ep.solve_count + ep.upsolve_count) * re.weight * rl.upsolve_weight ELSE ep.solve_count * re.weight + ep.upsolve_count * re.weight * rl.upsolve_weight END), 0) FROM ranklist_event re JOIN events e ON e.id = re.event_id JOIN ranklists rl ON rl.id = re.ranklist_id JOIN event_performance ep ON ep.event_id = re.event_id AND ep.user_id = ranklist_user.user_id WHERE re.ranklist_id = ranklist_user.ranklist_id) WHERE ranklist_id = NEW.ranklist_id AND user_id = NEW.user_id; UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = NEW.ranklist_id; END;
--> statement-breakpoint
CREATE TRIGGER `rl_score_ru_ad` AFTER DELETE ON `ranklist_user` BEGIN UPDATE ranklist_user SET rank = (1 + (SELECT COUNT(*) FROM ranklist_user r2 WHERE r2.ranklist_id = ranklist_user.ranklist_id AND r2.score > ranklist_user.score)) WHERE ranklist_id = OLD.ranklist_id; END;
