-- Auto-add membership is based only on event_performance in the 15 most recent
-- contest events attached to each ranklist. "Recent" is starting_at DESC with
-- id DESC as a deterministic tie-breaker. Attendance no longer affects membership.
--
-- This replaces the original 0007 triggers in place and reconciles existing
-- auto-added rows at the end. Manually added rows (auto_added = 0) remain untouched.

DROP TRIGGER IF EXISTS `rl_autoadd_ep_ai`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_ea_ai`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_ep_ad`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_ea_ad`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_re_ai`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_re_ad`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_rl_au_on`;
--> statement-breakpoint
DROP TRIGGER IF EXISTS `rl_autoadd_rl_au_off`;
--> statement-breakpoint

CREATE TRIGGER `rl_autoadd_ep_ai` AFTER INSERT ON `event_performance` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT re.ranklist_id, NEW.user_id, 1 FROM ranklist_event re JOIN ranklists rl ON rl.id = re.ranklist_id WHERE re.event_id = NEW.event_id AND rl.auto_add_users = 1 AND NEW.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = re.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_ep_ad` AFTER DELETE ON `event_performance` BEGIN DELETE FROM ranklist_user WHERE auto_added = 1 AND user_id = OLD.user_id AND (NOT EXISTS (SELECT 1 FROM ranklists rl WHERE rl.id = ranklist_user.ranklist_id AND rl.auto_add_users = 1) OR NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = ranklist_user.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15))); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_ep_au_event` AFTER UPDATE OF `event_id` ON `event_performance` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT rl.id, NEW.user_id, 1 FROM ranklists rl WHERE rl.auto_add_users = 1 AND rl.id IN (SELECT re.ranklist_id FROM ranklist_event re WHERE re.event_id = OLD.event_id OR re.event_id = NEW.event_id) AND EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = NEW.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = rl.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); DELETE FROM ranklist_user WHERE auto_added = 1 AND user_id = OLD.user_id AND ranklist_id IN (SELECT re.ranklist_id FROM ranklist_event re WHERE re.event_id = OLD.event_id OR re.event_id = NEW.event_id) AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = ranklist_user.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_re_ai` AFTER INSERT ON `ranklist_event` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT NEW.ranklist_id, ep.user_id, 1 FROM event_performance ep WHERE EXISTS (SELECT 1 FROM ranklists rl WHERE rl.id = NEW.ranklist_id AND rl.auto_add_users = 1) AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = NEW.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY ep.user_id; DELETE FROM ranklist_user WHERE ranklist_id = NEW.ranklist_id AND auto_added = 1 AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = NEW.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_re_ad` AFTER DELETE ON `ranklist_event` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT OLD.ranklist_id, ep.user_id, 1 FROM event_performance ep WHERE EXISTS (SELECT 1 FROM ranklists rl WHERE rl.id = OLD.ranklist_id AND rl.auto_add_users = 1) AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = OLD.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY ep.user_id; DELETE FROM ranklist_user WHERE ranklist_id = OLD.ranklist_id AND auto_added = 1 AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = OLD.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_re_au_event` AFTER UPDATE OF `ranklist_id`, `event_id` ON `ranklist_event` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT rl.id, ep.user_id, 1 FROM ranklists rl JOIN ranklist_event affected_re ON affected_re.ranklist_id = rl.id JOIN event_performance ep ON ep.event_id = affected_re.event_id WHERE rl.auto_add_users = 1 AND (rl.id = OLD.ranklist_id OR rl.id = NEW.ranklist_id) AND affected_re.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = rl.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY rl.id, ep.user_id; DELETE FROM ranklist_user WHERE auto_added = 1 AND (ranklist_id = OLD.ranklist_id OR ranklist_id = NEW.ranklist_id) AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = ranklist_user.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_rl_au_on` AFTER UPDATE OF `auto_add_users` ON `ranklists` WHEN NEW.auto_add_users = 1 AND OLD.auto_add_users = 0 BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT NEW.id, ep.user_id, 1 FROM event_performance ep WHERE ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = NEW.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY ep.user_id; DELETE FROM ranklist_user WHERE ranklist_id = NEW.id AND auto_added = 1 AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = NEW.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_rl_au_off` AFTER UPDATE OF `auto_add_users` ON `ranklists` WHEN NEW.auto_add_users = 0 AND OLD.auto_add_users = 1 BEGIN DELETE FROM ranklist_user WHERE ranklist_id = NEW.id AND auto_added = 1; END;
--> statement-breakpoint
CREATE TRIGGER `rl_autoadd_event_au_recent` AFTER UPDATE OF `starting_at`, `type` ON `events` BEGIN INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT rl.id, ep.user_id, 1 FROM ranklists rl JOIN ranklist_event eligible_re ON eligible_re.ranklist_id = rl.id JOIN event_performance ep ON ep.event_id = eligible_re.event_id WHERE rl.auto_add_users = 1 AND rl.id IN (SELECT affected_re.ranklist_id FROM ranklist_event affected_re WHERE affected_re.event_id = NEW.id) AND eligible_re.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = rl.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY rl.id, ep.user_id; DELETE FROM ranklist_user WHERE auto_added = 1 AND ranklist_id IN (SELECT affected_re.ranklist_id FROM ranklist_event affected_re WHERE affected_re.event_id = NEW.id) AND NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = ranklist_user.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)); END;
--> statement-breakpoint

-- Reconcile production data created under the original attendance-or-performance rule.
INSERT OR IGNORE INTO ranklist_user (ranklist_id, user_id, auto_added) SELECT rl.id, ep.user_id, 1 FROM ranklists rl JOIN ranklist_event re ON re.ranklist_id = rl.id JOIN events e ON e.id = re.event_id JOIN event_performance ep ON ep.event_id = re.event_id WHERE rl.auto_add_users = 1 AND e.type = 'contest' AND re.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = rl.id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15) GROUP BY rl.id, ep.user_id;
--> statement-breakpoint
DELETE FROM ranklist_user WHERE auto_added = 1 AND (NOT EXISTS (SELECT 1 FROM ranklists rl WHERE rl.id = ranklist_user.ranklist_id AND rl.auto_add_users = 1) OR NOT EXISTS (SELECT 1 FROM event_performance ep WHERE ep.user_id = ranklist_user.user_id AND ep.event_id IN (SELECT recent_re.event_id FROM ranklist_event recent_re JOIN events recent_e ON recent_e.id = recent_re.event_id WHERE recent_re.ranklist_id = ranklist_user.ranklist_id AND recent_e.type = 'contest' ORDER BY recent_e.starting_at DESC, recent_e.id DESC LIMIT 15)));
